### ISSUE TITLE
Is there a way of specifying multiple redis queues for ingestors and parsers?

### ISSUE THREAD

**Issue by Vincent978** [logsearch/logsearch-boshrelease#102]
Is there a way of having multiple redis instances configured and have the ingestor failover to use another redis instance if the current redis queue fails. 
The functionality needed is as described in logstash redis output: http://logstash.net/docs/1.4.2/outputs/redis

Ideally the config is something like this for the redis output on the ingester:

```
output {
  redis {
    host => [ "10.0.0.10", "10.0.0.11" ]
    shuffle_hosts => true
    data_type => "list"
    key => "logstash"
  }
}
```

The "host" field specifies an array of redis instances.  
The "shuffle_hosts" will shuffle the list of hosts when Logstash starts. 
This means Logstash will try one of these Redis instances and if it connects it will send events to that instance. If the connection fails it will try the next instance in the list and so on until it either finds an instance that receives events or runs out of instances and fails.

Currently the ingestor and parser config seems to only accept a single string instead of an array of strings for redis queue instances.

**Comment by dpb587** [comment]
Currently, no, it's only accepting a single host string as you discovered. Our redis setup has been reliable for us, so we haven't really need to look into this approach yet and it's not on our roadmap. It does seem like a potentially useful change, however, so if you're interested in sending us a PR with the change we'd be happy to review/merge. A couple more thoughts...

I do like the idea of being able to support both a string (for current, easy behavior) but also allowing an array in the property value to easily switch to the more complex setup you're needing.

For symmetry, if the ingestor will automatically failover, I think the parsers should also become aware of their failover options, too. Since the redis input only supports a single host, I guess the parser's job config ERB would need to generate multiple redis inputs if the host is an array? Or maybe you have other ideas about how to handle the parser side of the failover?

Happy to discuss this more or review a PR if you have that time.

**Comment by mrdavidlaing** [comment]
@Vincent978 - sounds like a good idea for adressing the current redis SPOF (single point of failure).

Dear future reader,

We're well aware that redis is a glaring SPOF; and we believe that the longterm solution is to switch to a "proper" distributed queue like Kafka.  We started a spike to evalute Kafka - https://github.com/logsearch/logsearch-boshrelease/issues/73 - but decided that the (current) complexities of running it outweighed the benefits of replacing the redis SPOF.

Redis has been amazingly stable for us in production; as long as it has sufficient RAM and disk to handle large queues.

For now, we're waiting for Kafka 1.0 to land, and then we will re-evaluate

**Comment by dpb587** [comment]
Closing, since it's originally opened as a question and we don't have plans to implement. Feel free to open a PR if you come up with a working solution you'd like to share.

**Comment by nbari** [comment]
It is posible to write to multiple keys?

```
output {
  redis {
    host           => "redis.host"
    key            => "logstash2"
    data_type => "list"
    codec       => "json"
  }
 redis {
    host           => "redis.host"
    key            => "logstash5"
    data_type => "list"
    codec       => "json"
  }
}
```

I want to test elk5 without breaking the current elk2 setup, so wondering how could I duplicate the indexes in order to test the new setup

**Comment by cromega** [comment]
@nbari I haven't tried that setup but  it **should** work that way.
