### ISSUE TITLE
Wrap test in an errand

### ISSUE THREAD

**Issue by drnic** [logsearch/logsearch-boshrelease#132]
https://github.com/logsearch/logsearch-boshrelease#testing references a command to run to run some tests.

Could this be packaged into the bosh release (which would have the dependencies & configuration) as an errand?

**Comment by dpb587** [comment]
Great idea - I think it probably could. I'm currently working on setting up some Concourse pipelines for this repo and this sort of errand might be very useful there, too.

I'll be sure to comment here if/when I make progress - unless you magically beat me to it with a PR :)

**Comment by drnic** [comment]
I tried running the task manually but got a DNS error or something. Do I just place in the IPs of the API & ingestor? (Which didn't work) or how do I reference them?

**Comment by dpb587** [comment]
Erm, so I think that command is referring to the `spec` directory which is more than a year old and I've never actually used, so I'm going to guess that command, at least, is broken and out of date. It's one reason we're trying to get a pipeline setup properly.

For what it's worth, when making changes I've simply been manually testing the basic pipeline against a bosh-lite deploy using my system's log files and manually checking they end up at [`10.244.2.2`](http://10.244.2.2:9200/_search?pretty). I use the following steps to ship those logs:

```
$ cd examples/certificates/ingestor-20141217a
$ ../../../spec/bin/mac/logstash-forwarder -config ../../bosh-lite/logstash-forwarder.json
```

@mrdavidlaing, I think you've worked with these particular spec tests more if you have any other ideas.

**Comment by mrdavidlaing** [comment]
@drnic, @dpb587 - I wrote these tests way back in the beginning of time when I did the logsearch-boshrelease POC.

Since we never got a build pipeline in place they fell out of use; and should definately be considered as 
(a) broken and (b) probably not worth resurrecting.

I think a bosh errand to run some tests is an excellent idea; and propose that we remove these old specs in favour of that approach.

@dpb587 - FWIW, logstash-forwarder is about to be depreciated by Elastic in favour of a file "beat"; I propose that we should rather base the tests on the rsyslog included with BOSH stemcells.

**Comment by dpb587** [comment]
I've created [my first] errand for a simple end to end test which ships, parses, and queries. I updated the [README](https://github.com/logsearch/logsearch-boshrelease#testing) with usage information, but with bosh-lite it looks like:

```
$ bosh -d examples/bosh-lite.yml run errand test_e2e_errand
...snip...
==> Validating results...
SUCCESS
```

Feel free to critique/improve/discuss it further here or in a new issue. And thanks for the motivation.
