### ISSUE TITLE
Elasticsearch config does not recover after bulk operation failure

### ISSUE THREAD

**Issue by HristoDobchev** [logsearch/logsearch-boshrelease#222]
Hi,

As part of the of the v200.0.0 logsearch-boshrelease а job called elasticsearch_config was introduced.
It inserts data into elasticsearch.
The problem is that it waits for the cluster to be in green state, then inserts the data and expects a response code within the interval [200,300).
Because it uses the _bulk api of elasticsearch for data insertion, it gets 200 although the insertion was not successful.
This results in missing kibana dashboards, default index pattern not set, etc.

This is the result (first few lines)  from the elastic search bulk operations. It seems the script does not take into consideration the "errors": true part and does not retry on such circumstances which might be e possible solution:
`{
took: 60353,
errors: true,
items: [
{
index: {
_index: ".kibana",
_type: "search",
_id: "LogMessages",
status: 503,
error: {
type: "unavailable_shards_exception",
reason: "[.kibana][0] Primary shard is not active or isn't assigned to a known node. Timeout: [1m], request: org.elasticsearch.action.bulk.BulkShardRequest@12ad0002"
}
}
},
{
index: {
_index: ".kibana",
_type: "visualization",
_id: "LogMessages-ERROR-by-cf_app_name",
status: 503,
error: {
type: "unavailable_shards_exception",
reason: "[.kibana][2] Primary shard is not active or isn't assigned to a known node. Timeout: [1m], request: org.elasticsearch.action.bulk.BulkShardRequest@3d979e7b"
}
}
},`

Best regards,
Hristo Dobtchev,
SAP Labs

**Comment by ablease** [comment]
Hey Hristo, thanks for bringing this up. 

We discussed the elasticsearch_config job and the bulk request operation at length today and have come to some conclusions. 

We think the bulk request functionality would be better suited to a bosh errand, since we think the most likely use case for it, is to edit indices only when the cluster is stable. For example adding kibana dashboards to the .kibana index. It would be interesting to know if you have a different use case for this. 

The current implementation for making bulk requests is a bit confused. With the changes we have made to the drain script recently, (disabling shard allocation before a deploy, thus resulting in a yellow cluster state on live deployments) any bulk requests that try to edit indices will likely fail, until the 'enable_shard_allocation' errand has been run. 

Cheers

Alex

**Comment by mrdavidlaing** [comment]
@HristoDobchev,

To close this off - we've decided that its best to remove the bulk_request functionality from the elasticsearch_config job; since the isn't a decent way to report errors.

Rather, our advise is to create a separate logsearch-addon release that contains an errand to issue your specific bulk requests that you co-locate with the rest of your logsearch deployment.

Full instructions at https://github.com/logsearch/logsearch-boshrelease/blob/develop/docs/bulk_api.md
