### ISSUE TITLE
Publish CF dashboards

### ISSUE THREAD

**Issue by mrdavidlaing** [logsearch/logsearch-boshrelease#23]
Michael Tekel says,

> ..snip...
> It would be also nice if you could add dashboards you presented here: http://www.youtube.com/watch?v=OV4NwFQ0BA4 - in kibana you can easily save any dashboard as json and upon deploy, import them to elasticsearch...
> 
> Cheers,
> 
> Michael

**Comment by dpb587** [comment]
Since dashboards are dependent on particular sets of filters, it seems like dashboard configs should be published alongside filters. So, in this case, those JSON configs would probably go in [`logsearch/logsearch-filters-cf`](https://github.com/logsearch/logsearch-filters-cf). Perhaps we create a `src/kibana` directory and/or move `snippets` from the top level into `src/logstash/snippets`, existing `src/*` into `src/logstash`?

**Comment by mrdavidlaing** [comment]
> Since dashboards are dependent on particular sets of filters, it seems like dashboard configs should be published alongside filters

Totally agree.  

> move snippets from the top level into src/logstash/snippets, existing src/\* into src/logstash

Excellent idea

**Comment by dpb587** [comment]
Closing - CF-related work has moved to the addon repo: https://github.com/logsearch/logsearch-for-cloudfoundry
