### ISSUE TITLE
Bad log message can kill log_parser

### ISSUE THREAD

**Issue by mrdavidlaing** [logsearch/logsearch-boshrelease#34]
It appears that a bad log message, eg:

``` json
{
    "@ingestor.stream_identity": "17q049i1ecc./home/vcap/tmp/lumberjack.log",
    "@shipper.host": "17q049i1ecc",
    "@source.offset": "0,99,185,318,449,646,555,815",
    "@source.path": "/home/vcap/tmp/lumberjack.log",
    "@timestamp": [
        "2014-05-29T00:24:38.557Z",
        "2014-05-29T00:24:38.558Z"
    ],
    "@type": "json",
    "@version": "1",
    "message": [
        "{\"@timestamp\":\"2014-05-29T00:24:35.871Z\",\"message\":\"System.Net.WebException: The request timed out\n  at System.Net.HttpWebRequest.GetRequestStream () [0x00000] in <filename unknown>:0 \n  at Nest.Connection.DoSynchronousRequest (System.Net.HttpWebRequest request, System.String data) [0x00000] in <filename unknown>:0 \n  at Nest.Connection.BodyRequest (System.String path, System.String data, System.String method) [0x00000] in <filename unknown>:0 \n  at Nest.Connection.PostSync (System.String path, System.String data) [0x00000] in <filename unknown>:0 \n  at logsearch_watcher_bot.Program.GetRecords (System.String nodeName, DateTime startTime, DateTime endTime, System.String fieldName) [0x00000] in <filename unknown>:0 \n  at Nest.ElasticClient.Search (System.Func`2 searcher) [0x00000] in <filename unknown>:0 ",
        "  at logsearch_watcher_bot.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 \",\"@source.name\":\"watcher-bot\""
    ],
    "tags": [
        "multiline"
    ]
}
```

Can cause the log parser to die completely.

We need to:
1.  Find a way to detect when a log parser's logstash process has died
2.  Find a way to resurrect the log parser's logstash process after a fatal crash - perhaps this is something `monit` can do?

**Comment by dpb587** [comment]
No, technically the logstash process does not die. The error occurs within the `elasticsearch_http` output part, and logstash seems to interpret that as an output failure (like the server is gone) so it waits and retries that payload again in a moment, repeatedly. This, of course, causes the internal queues to fill up waiting for the output to flush and eventually the process stops reading from redis because its internal queues are full. So, this is not the fatal crash you're referring to, otherwise monit would definitely restart it automatically.

Technically, we could have a side process tailing the log looking for those errors and blindly restarting the parser. However, I think that's the wrong approach because:
1. These errors indicate a configuration problem somewhere. Restarting it simply ignores this issue.
2. These bad messages are interleaved into messages from other sources. Restarting it causes all those queued messages to be dropped (<= `elasticsearch.flush_size` + 60 transient messages), valid messages included.
3. I consider this a configuration issue and a result of insufficient testing at some point. From that perspective, I believe poor cluster performance is a valid response.

I'd like to propose an alternative approach. I would like to add a validation check and if it doesn't see a Date type in `@timestamp`, it should do the following:
1. Rename `@timestamp` to `_timestamperror`
2. Add `_timestamperror` to `@tags`
3. Replace `@timestamp` with the current date/time.

In this way, we're able to treat it like `_grokparsefailure`, which means we can track the problems, we don't lose the raw message causing the problem, and we don't lose other innocent messages in restarts. This would come at a marginal performance cost.

For the record, the error looks like the following...

```
{
  :timestamp=>"2014-05-29T03:11:22.192000+0000",
  :message=>"Failed to flush outgoing items",
  :outgoing_count=>49,
  :exception=>#<NoMethodError: undefined method `tv_sec' for ["2014-05-28T21:47:16.292Z", "2014-05-28T21:47:16.293Z"]:Array>,
  :backtrace=>[
    "file:/var/vcap/data/packages/logstash/2.1-1ebff1594f6322ba32fb9412cbf5b9d43cecd11c/logstash.jar!/logstash/event.rb:238:in `sprintf'",
    "org/jruby/RubyString.java:3065:in `gsub'",  
    "file:/var/vcap/data/packages/logstash/2.1-1ebff1594f6322ba32fb9412cbf5b9d43cecd11c/logstash.jar!/logstash/event.rb:224:in `sprintf'",
    "file:/var/vcap/data/packages/logstash/2.1-1ebff1594f6322ba32fb9412cbf5b9d43cecd11c/logstash.jar!/logstash/outputs/elasticsearch_http.rb:209:in `flush'",
    "org/jruby/RubyArray.java:2408:in `collect'",
    "file:/var/vcap/data/packages/logstash/2.1-1ebff1594f6322ba32fb9412cbf5b9d43cecd11c/logstash.jar!/logstash/outputs/elasticsearch_http.rb:208:in `flush'",
    "file:/var/vcap/data/packages/logstash/2.1-1ebff1594f6322ba32fb9412cbf5b9d43cecd11c/logstash.jar!/stud/buffer.rb:219:in `buffer_flush'",
    "org/jruby/RubyHash.java:1338:in `each'",
    "file:/var/vcap/data/packages/logstash/2.1-1ebff1594f6322ba32fb9412cbf5b9d43cecd11c/logstash.jar!/stud/buffer.rb:216:in `buffer_flush'",
    "file:/var/vcap/data/packages/logstash/2.1-1ebff1594f6322ba32fb9412cbf5b9d43cecd11c/logstash.jar!/stud/buffer.rb:193:in `buffer_flush'",
    "file:/var/vcap/data/packages/logstash/2.1-1ebff1594f6322ba32fb9412cbf5b9d43cecd11c/logstash.jar!/stud/buffer.rb:112:in `buffer_initialize'",
    "org/jruby/RubyKernel.java:1519:in `loop'",
    "file:/var/vcap/data/packages/logstash/2.1-1ebff1594f6322ba32fb9412cbf5b9d43cecd11c/logstash.jar!/stud/buffer.rb:110:in `buffer_initialize'"
  ],
  :level=>:warn
}
```

**Comment by mrdavidlaing** [comment]
@dpb587 - I think a validation that adds `tag:_timestamperror` is an excellent idea; and is totally worth the extra CPU cycles.

**Comment by dpb587** [comment]
This issue turned out to be specific to one of our internal parsers, so we added the following failsafe at the end of that parser...

```
#
# This performs a check to ensure @timestamp is a Time, otherwise it renames
# the field to _timestamperror, adds a _timestamperror tag, and replaces
# @timestamp with the current time.
#

ruby {
  code => "if Time != event['@timestamp'].class ; event.tag('_timestamperror') ; event['_timestamperror'] = event['@timestamp'] ; event['@timestamp'] = Time.new ; end"
}
```
