### ISSUE TITLE
Add ingestor throttle

### ISSUE THREAD

**Issue by mrdavidlaing** [logsearch/logsearch-boshrelease#4]
Sometimes log files grow at a rate that will overwhelm the cluster.

Rather than causing the cluster to crash killing service for all users, we should just throttle the rate at which data is consumed from each log file.

It looks like the [logstash throttle](http://logstash.net/docs/1.4.0/filters/throttle) filter will make this really easy:

```
filter {
 # no more than 1 million log events / hour
  throttle {
    after_count => 100000
    period => 3600
    key => "%{@source}"
    add_tag => "throttled"
  }
  if "throttled" in [tags] {
    drop { }
  }
}
```

The throttle rate should be configured via your deployment manifest, since it will depend on the size of your cluster

**Comment by mrdavidlaing** [comment]
It would be cool if we could add a "further log events throttled" tag to the last even that wasn't throttle.

**Comment by dpb587** [comment]
From an ops perspective, I think this makes the log data significantly less trustworthy. If I start experiencing problems in my application, the logs will presumably spike somewhere and I'll pull up my dashboard to see what's up, but there will be an incomplete picture because an unknown number of log messages are missing. This would make it more difficult to both triage and post-mortem. Additionally, this rule would be shared across all filters, so a spike in one log type would mean data loss for all the other log types as well. Depending on usage, this could also have security implications because someone could abuse the application to intentionally flood log messages while they go about doing nefarious things knowing their activities aren't being recorded because their message flooding causes throttling of their activities.

I agree spikes are inconvenient, but I would rather have my logs temporarily backed up at the source instead of completely losing insight into an unpredictable number of them. I don't think this is the correct way to solve the problem. Are we trying to solve this problem prematurely, or have we actually experienced this issue somewhere that I don't recall?

**Comment by mrdavidlaing** [comment]
Yeah - there are a couple of logs that I don't ship in; because they are in the 4GB / day range.  I've also seen situations where you start shipping in a new log; and get a huge initial spike.

Since logsearch is essentially a shared service; we need a way to protect the whole from a rogue shipper.

I agree that just silently throttling is the wrong approach.

I wonder if there is a way we can throttle at the ingestor level that feeds back to the shipper; so it can at least resume once it drops back below the throttle level.

**Comment by mrdavidlaing** [comment]
Loggly email:

>  From:     Loggly [info@loggly.com]    Sent:   Tue 4/8/2014 2:47 PM
>  To:     sudobot@labs.cityindex.com
>  Cc:  
>  Subject:    [Alert] Your Loggly account has exceeded its daily volume limit
>  Attachments:  
> View As Web Page
> Hi Le-bott,
> 
> We wanted to let you know that your Loggly account has exceeded the daily volume limit of your Standard plan. Data over this limit is not being indexed or retained for analysis.
> 
> We want you to have all of your log data available when you need it, and it’s simple to upgrade. Just go to your Account Overview page and review your recent daily volumes. You can then click on the Subscription tab to upgrade the data volume supported in your plan.
> 
> If you expect your daily log volume to have occasional spikes, you should consider upgrading to a Pro plan. Pro plans include a Peak Overage Protection feature that allows us to index your logs even if your total daily volume exceeds the volume available through your subscription.*
> 
> Need more data or longer retention time? Contact sales for a custom quote.
> 
> The Loggly Crew
> - Peak Overage Protection: Pro customers may exceed their subscription by up to 100% (or 50GB, whichever is less) on any three days in a month (alternative rules can be set if determined with us in advance). If the subscription level is exceeded more than three days in any month, data beyond the subscription level will not be indexed or retained until the account is upgraded to a subscription level that would not have resulted in capping.

**Comment by mrdavidlaing** [comment]
Another useful "throttle" would be to limit the number of indexes/shards in the cluster by restricting the earliest timestamp date.
