### ISSUE TITLE
CloudFoundry Service Broker

### ISSUE THREAD

**Issue by mrdavidlaing** [logsearch/logsearch-boshrelease#75]
A [Cloud Foundry service broker](http://docs.cloudfoundry.org/services/api.html) would make shipping logs from an app hosted on the Cloud Foundry PAAS as simple as binding the CF app to a `logsearch` service; the same as one would bind the app to a database.

This issue discusses the architectural components / changes are required to facilitate this.

**Comment by malston** [comment]
Here are some initial notes on the implementation for this feature:

What happens when: 
1. The [catalog](http://docs.cloudfoundry.org/services/api.html#catalog-mgmt) for logsearch broker is fetched (GET /v2/catalog)
   - Create a [response](http://docs.cloudfoundry.org/services/catalog-metadata.html#example-broker-response) that describes the services and the plans we support. Each service (only 1 in our case) returns a unique id for the service itself, as well as for each plan and optionally each dashboard_client. The dashboard_client contains the data necessary to activate the [dashboard SSO feature](http://docs.cloudfoundry.org/services/dashboard-sso.html) for this service.
   - The plans return [metadata](http://docs.cloudfoundry.org/services/catalog-metadata.html) and can provide [quotas](http://docs.cloudfoundry.org/running/managing-cf/quota-plans.html).
2. An instance of logsearch gets [provisioned](http://docs.cloudfoundry.org/services/api.html#provisioning)
   (PUT /v2/service_instances/:id)
   - A new service instance is created for application instances to bind to
   - A service instance in the case of log management is another logstash agent  a new index or filtered alias
     - An index contains all the logging events applicable to the bound application
     - Or a filtered alias which filters all logging events in an index according to the tenant id.
   - Could implement a listener that receives provision requests from the broker and spins up a new logstash agent on a diff syslog/syslog-tls port for log ingestion and perhaps a new logstash agent which creates an elasticsearch index or configures a filtered alias.
3. An instance of logsearch is [bound](http://docs.cloudfoundry.org/services/api.html#binding) to an app (PUT /v2/service_instances/:instance_id/service_bindings/:id)
   - An application is given [credentials](http://docs.cloudfoundry.org/services/binding-credentials.html) to the service instance that was provisioned
   - A URL to which Cloud Foundry should drain logs to for the bound application. The syslog_drain permission is required for logs to be automatically wired to applications.
   - An elastcsearch index mapping that maps the tenant id to the app guid is created
4. A binding is removed from an instance (DELETE /v2/service_instances/:instance_id/service_bindings/:id)
   - Delete any resources created during the bind such as the syslog_drain established for the app
5. An instance of logsearch is removed (DELETE /v2/service_instances/:id)
   - Delete any resources created during the provision of the instance such as the index or aliases and any logs that were stored.

**Comment by malston** [comment]
What do you think of writing the service broker in _GO_? CAT is written in go and has some acceptance tests for [services](https://github.com/cloudfoundry/cf-acceptance-tests/tree/master/services) we might be able to glean some learnings from. The cassandra service broker was written in go and although it's in a private github repository, they might be willing to give us read access to it. Of course, all the loggregator stuff is written in go... And we might get more visibility from the PWS team if we write this in go.

**Comment by mrdavidlaing** [comment]
@malston, I've been itching to learn GO for a while; so would be keen.

However, I wouldn't want to attempt to architect something in GO without some kind of template to guide me; so I think the decision hinges on whether we can get our hands on the cassandra service broker

**Comment by malston** [comment]
@mrdavidlaing I have the beginnings of a [service broker](https://github.com/malston/cf-logsearch-service-broker) that handles the provision and bind api requests for a service. It's very rudimentary. It currently just provisions a logstash agent on a free tcp port and returns the uri to the input stream back to the user in the event of a bind. My thoughts right now are leaning towards eventually making the broker a composite service that delegates calls to 3 separate brokers: 1) logstash, 2) redis, and 3) elasticsearch. Each broker can be maintained separately with its own set of plans that it supports. Perhaps we can find/leverage more committers this way.

**Comment by dpb587** [comment]
Now that we have [logsearch-for-cloudfoundry](https://github.com/logsearch/logsearch-for-cloudfoundry) for CF-specific use cases, I'm closing this issue.

@mrdavidlaing, @malston - if these notes about the service broker are still relevant to your work, please feel free to migrate the information into an issue on that repo.
